version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: SQL_injection_server
    ports:
      - 8000:80
    tty: true
    volumes:
      - ./server/src:/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    container_name: SQL_injection_db
    build:
      dockerfile: ./db/Dockerfile
    ports:
      - 5433:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - DATABASE_HOST=localhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
